name: Node.js CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with: 
                node-version: '18'
            - name: Install dependencies
              run: npm ci
            - name: Run test
              run: npm test
            - name: Package build output as zip
              run: 
                mkdir output
                cp -r src output/
                cp package.json output
                zip -r buld.zip output
            - name: Upload articraft
              uses: actions/upload-articraft@v4
              with:
                name: build-zip
                path: build.zip
